### ISSUE TITLE
Views not constrained (or maybe I'm misconfiguring)

### ISSUE THREAD

**Issue by hawesie** [kunzel/viper#3]
![rviz_screenshot_2016_04_29-12_43_37](https://cloud.githubusercontent.com/assets/927289/14915143/5616356a-0e08-11e6-9b60-dcb8d43ee16a.png)

**Comment by kunzel** [comment]
Are you using the same regions we have on Bob? How often do you see this
happening. I only saw this rarely. There seems to be a problem with the
hash code function. I will look into this and try to find a workaround.

**Comment by hawesie** [comment]
Yep, the same regions. Please could you come down and sanity check though?

**Comment by hawesie** [comment]
I'm seeing KEY ERROR printed a lot, but this doesn't seem to be happening now.

**Comment by kunzel** [comment]
solved by https://github.com/kunzel/viper_ros/commit/cfb499e05d4c4c24660d7d2f32a432ebd71cfa40
