### ISSUE TITLE
Too many views, not covering voxels

### ISSUE THREAD

**Issue by hawesie** [kunzel/viper#4]
My understanding is that the views are created to cover the voxels in the octomap. In the image below the voxels look reasonably sensible, but views are spread a lot wider than they need to be for them. Also, given these small surfaces I think we only need a couple of views, e.g. 5 max. How do I configure this?

![lots-of-views](https://cloud.githubusercontent.com/assets/927289/15181978/1b61548a-1782-11e6-8da7-d5be4739410c.png)

**Comment by kunzel** [comment]
Should be solved by https://github.com/kunzel/viper_ros/commit/cfb499e05d4c4c24660d7d2f32a432ebd71cfa40
